with open('Codingal (1).txt', 'r') as file:
    print("Gaming might seem irrelivant to coding but actually it is made out of code so let us apreciate those who created or favourite games")
    print(file.read())

with open ('Codingal (1).txt', 'w') as file:
    file.write("Math might seem irrelivant in football but actually it is used  to calculate when to shoot and when to curve the ball")
    file.write(" The content is outstanding")


with open ('Codingal (1).txt', 'a') as file:
    file.write(" \n You might think names dont have meaning but they actually \n")
    file.write(" \nThe content is outstanding\n")